name: Build
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, blacksmith-4vcpu-ubuntu-2204, macos-13]
    env:
      # https://github.com/NuGet/Home/issues/11548
      # https://twitter.com/xoofx/status/1488617114940452872?s=20&t=BKSN4j9rP6fOyg8l7aW0eg
      NUGET_CERT_REVOCATION_MODE: offline
    steps:
      - name: Get Source
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install .NET Core SDK
        uses: useblacksmith/setup-dotnet@v5
        with:
          include-prerelease: true
          dotnet-version: |
            3.1.x
            8.0.x
      - name: Build and Test
        run: dotnet test --logger "trx;LogFileName=test-results.trx"
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results-${{ matrix.os }}
          path: '**/test-results.trx'