name: 'Test Report'
on:
  workflow_run:
    workflows: [ 'Build' ]
    types:
      - completed
jobs:
  report:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    strategy:
      matrix:
        os: [windows-latest, blacksmith-4vcpu-ubuntu-2404, macos-latest]
    steps:
      - name: Process Test Results
        uses: dorny/test-reporter@v1
        with:
          artifact: test-results-${{ matrix.os }}
          name: 'Test Results (${{ matrix.os }})'
          path: '**/*.trx'
          reporter: dotnet-trx
